### ISSUE TITLE
New tables *can* have NOT NULL on creation

### ISSUE THREAD

**Issue by tonythomas01** [3YOURMIND/django-migration-linter#16] opened 2018-05-04 13:45 UTC
The tool cries when you try to add a new table with a NOT NULL. This is not nice, and should be improved. 

Eg: 
new Table A with a FKey which cannot be NULL --> should be fine 
new Table A with a field that cannot be NULL --> should be fine.

**Comment by David-Wobrock** [comment] 2018-05-07 18:39
Hi there,

Could you be more specific please?
Take a look at this commit https://github.com/3YOURMIND/django-migration-linter/commit/73644550731ad51fc87015f2c46a4f62d2685d47
I added what I understood from your comment, and the linter seems to be fine with the added test.

Might it be linked to the backend you are using? We only test against a Mysql database currently.

**Comment by David-Wobrock** [comment] 2018-07-19 19:24
Closing since for now since I cannot reproduce.
Don't mind re-opening it if you can provide an example or just more info.

Cheers

**Closed by David-Wobrock** 2018-07-19 19:24 UTC
