### ISSUE TITLE
Alternative functionality to "since this commit"

### ISSUE THREAD

**Issue by chaduhduh** [3YOURMIND/django-migration-linter#88] opened 2019-12-27 23:47 UTC
I need similar functionality to the "since this commit" commit ID parameter but since I will be running this within a container I will not have access to the git repository. I can manually determine which migrations are new but once I have the list I cannot use them with the current functionality (aside from running the lint once for each name).

I have a couple ideas on how this could be achieved:

1. Adjust --ignore-name-contains or --ignore-name parameters to accept a list of values. This way one could pass in all the migration names to ignore
2. Utilize the sequential Django migration numbers and add a "since this migration" parameter that would work similar to "since this commit". This way one could pass a migration number such as 0006, and the linter would run from 0007 through _n_ migrations.

Im curious what your thoughts are on this. Im going to explore using the unapplied-migrations flag for now but in a test environment that configures a mock database this wont work since all migrations will be applied or unapplied.

**Comment by David-Wobrock** [comment] 2019-12-30 09:57
Hi Chadd,
Thank for the suggestions!

I think that the first idea, of being able to pass multiple parameters to these options, already partially works. `--ignore-name-contains` accepts only one parameter, but `--ignore-name` can take multiple names that will all be ignored.
So one possibility would be to implement on your side some logic that will pass all existing migrations to the call to the migration linter in this option.

That would be a potential workaround.

I like the second suggestion of leveraging the migration numbers and order. But that is not _so_ simple as a "sequential" Django migration, because the order of migrations is actually defined inside the migration code, and merge migration and inter-app dependencies can bring some complexity in there. But generally, leveraging the migration tree is a smart idea :+1: And since we rely on Django, this tree has already been built-in by the framework, so we can just read that information to decide which migrations to lint :thinking: 
I'll try to reflect on that in the next days/weeks and suggest an implementation that could work.

Thanks a lot!

**Comment by chaduhduh** [comment] 2019-12-30 16:34
Thank you for the reply David. 

I didn't realize that --ignore-name can take multiple names so that will work perfectly for me. I will give that a try 🙏 

For the Django migration numbers suggestion; I realized after suggesting that it is a bit more complex than it seemed at first. Particularly as you mentioned the app dependencies, I was only considering it on the scale of a single app within a project. I will also explore this a little bit and see if I can come up with a decent solution and can submit PR if so.

It is your call if you want to leave this open or close it as I think --ignore-name parameter will actually achieve what I was needing. I would, however, be curious to see the other implementation because I think it might be more explicit for my particular use case.

Thanks again!

**Comment by David-Wobrock** [comment] 2019-12-30 21:36
I'll keep this open for now! The issue is definitely interesting and it would be nice if the migration linter could avoid having you write custom logic as much as possible in order to make it run on new migrations only.

I'd be more than happy if you submitted a PR :100: 
As a hint for how to integrate in the linter source code (which is not that big admittedly), see https://github.com/3YOURMIND/django-migration-linter/blob/master/django_migration_linter/migration_linter.py#L103-L108 which selects which migrations have to be linted. We'll probably need to add a third path there, which will dig into the `self.migration_loader` object :)
And, obviously, add an option to select a specific migration

**Comment by David-Wobrock** [comment] 2021-05-26 17:20
I believe that, if you are able to have the migration file paths, you can write them to a file and pass the file name to the linter with the `--include-migrations-from` option.
This is available since https://github.com/3YOURMIND/django-migration-linter/releases/tag/v1.4.0
It should tell the linter only to check those migrations.

Closing the issue. Feel free to re-open an issue if you think another solution would be better or the issue persists.

**Closed by David-Wobrock** 2021-05-26 17:20 UTC
